site_name: mkdocs-plotly-plugin
site_description: "Mkdocs plugin to include charts in your site."
edit_uri: ''
repo_url: 'https://github.com/haoda-li/mkdocs-plotly-plugin'
repo_name: 'haoda-li/mkdocs-plotly-plugin'
copyright: 'Copyright &copy; 2023'
use_directory_urls: true

theme:
  name: material
  icon:
    logo: material/chart-box
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Dark mode
    - scheme: slate
      accent: green
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Light mode

nav:
  - Home: index.md
  - Gallery: gallery.md
  - Contributing: contributing.md

plugins:
  - search
  - plotly

use_directory_urls: true

markdown_extensions:
  - meta
  - admonition
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.tabbed:
      alternate_style: true 

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/haoda-li/
    - icon: fontawesome/brands/github
      link: https://github.com/haoda-li/
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=e1Bif78AAAAJ

copyright: Copyright &copy; 2017 - 2023 | Haoda Li